# Generated by Django 4.0.5 on 2022-06-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('product', models.CharField(max_length=60)),
                ('d_Date', models.DateField()),
                ('add', models.CharField(max_length=60)),
                ('price', models.FloatField()),
            ],
        ),
    ]
